# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0002_remove_post_boundedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boundedtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testblog.Tag'),
        ),
    ]
